version: "3.8"

services:
  database:
    image: postgres:12
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./tests/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/libs/postgresql/data/
    environment:
      POSTGRES_DB: family_budget
      POSTGRES_USER: family_budget
      POSTGRES_PASSWORD: family_budget
  app:
    build: .
    volumes:
      - ./.env:/root/.env:rw
    ports:
      - "8000:8000"
    environment:
      CONFIG_PATH: .env
      DB_HOST: database
    command: >
      bash -c "alembic upgrade head
      && poetry run python -m family_budget.main"
    depends_on:
      - database
    platform: linux/amd64

volumes:
  postgres_data:
