version: "3.8"

services:
  database:
    image: postgres:12
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./tests/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/libs/postgresql/data/
    environment:
      POSTGRES_DB: family_budget
      POSTGRES_USER: family_budget
      POSTGRES_PASSWORD: family_budget
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CONFIG_PATH: .env
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - database
    command: poetry run app
    platform: linux/amd64

volumes:
  postgres_data:
